from datetime import timedelta
from time import time
from glob import glob
from os.path import exists
from os import mkdir
from shutil import move
from colorama import Fore, init, Style
from cvlib import detect_common_objects
from cv2 import imread


bright = Style.BRIGHT
green, blue, red, cyan, reset = Fore.GREEN + bright, Fore.BLUE + bright, Fore.RED + bright, Fore.CYAN, Fore.RESET
init(convert=True, autoreset=True)


def img_cv_lib(image):
    global faces_num, no_faces_num
    face = imread(image)
    bbox, label, conf = detect_common_objects(face)
    if 'person' in label:
        faces_num += 1
        move(image, "faces")
    else:
        no_faces_num += 1
        move(image, "no_face")

def folder_list():
    folder = input('[+] Drag and drop the folder :- ').replace('"', '')
    if not folder:
        print(f"{red}[+] Enter the folder name correctly")
        folder_list()
    img = glob(f'{folder}/**/*.jpg', recursive=True) + (glob(f'{folder}/**/*.png', recursive=True)) + (glob(f'{folder}/**/*.jpeg', recursive=True))
    if not (img) or (len(img)==0):
        print(f"{red}[+] Folder is empty or incorrect folder name try again with new folder")
        folder_list()
    print(f"{green}[+] Total files in folder are {len(img)}")
    for img_file in range(len(img)):
        print(f'{blue}[{img_file + 1}] {green}processing the image {cyan}{img[img_file]}')
        try:
            img_cv_lib(img[img_file])
        except:
            print(f"{red}[-] Invalid image {img[img_file]}")

def credit():
    credit_text = f"""
               {red}CVLIB IMAGE SEPARATOR
{green}               
     ██▀███   ▄▄▄       ██░ ██  █    ██  ██▓    
    ▓██ ▒ ██▒▒████▄    ▓██░ ██▒ ██  ▓██▒▓██▒    
    ▓██ ░▄█ ▒▒██  ▀█▄  ▒██▀▀██░▓██  ▒██░▒██░    
    ▒██▀▀█▄  ░██▄▄▄▄██ ░▓█ ░██ ▓▓█  ░██░▒██░    
    ░██▓ ▒██▒ ▓█   ▓██▒░▓█▒░██▓▒▒█████▓ ░██████▒
    ░ ▒▓ ░▒▓░ ▒▒   ▓▒█░ ▒ ░░▒░▒░▒▓▒ ▒ ▒ ░ ▒░▓  ░
      ░▒ ░ ▒░  ▒   ▒▒ ░ ▒ ░▒░ ░░░▒░ ░ ░ ░ ░ ▒  ░
      ░░   ░   ░   ▒    ░  ░░ ░ ░░░ ░ ░   ░ ░   
       ░           ░  ░ ░  ░  ░   ░         ░  ░ {blue}code generated by Rahul.p\n
    """
    print(credit_text)

def main():
    global faces_num, no_faces_num
    print(f"{cyan}[*] Using cvlib for processing images")
    module_name = 'cvlib'
    faces_num, no_faces_num = 0, 0
    [mkdir(folder) for folder in ["no_face", "faces"] if not exists(folder)]
    folder_list()
    time_output = time() - start_time
    sec = str(timedelta(seconds=(int(time_output)))).split(":")
    print(f"[*]{green} Time taken to process images is -{reset} {sec[0]} H : {sec[1]} M : {sec[2]} S")
    print(f"{green}[~] Successfully completed [~]")
    print(f'{blue}[*] Using {module_name} \n{green}[+] faces are :- {faces_num}\n{red}[-] no faces are :- {no_faces_num}')

try:
    credit()
    start_time = time()
    main()
except KeyboardInterrupt:
    print(f'{red}\n[~] Exiting ....')
except Exception as e:
    print(f"{red}\n[-] error message is {e}")
